/* Autogenerated file. Do not edit manually. */

import { AccountInterface, BigNumberish} from 'starknet'
import {CustomDojoProvider} from "@/providers/CustomDojoProvider.ts";

export type IWorld = Awaited<ReturnType<typeof setupWorld>>;

export async function setupWorld(provider: CustomDojoProvider) {
  function actions() {
    const interact = async (
        { account, contract_name, call, calldata }: { account: AccountInterface, contract_name: string, call: string, calldata: BigNumberish[] }
    ) => {

      try {
        return await provider.execute(
          account,
          contract_name,
          call,
          calldata
        );
      } catch (error) {
        console.error("Error executing interact:", error);
        throw error;
      }
    };

    return { interact };
  }
  return {
    actions: actions(),
  };
}
