import { comment } from "postcss";

export const proposals = [
  {
    id: 1,
    title: "Adding A New Color: #FF00FF",
    proposer: "shora",
    forPoints: 4329,
    againstPoints: 30,
    status: "end in 5h30m",
    statusColor: "bg-green-500",
    comments: "This color is very important to me. I need it to express myself.",
  },
  {
    id: 2,
    title: "Extend the p/war event: 24 hours",
    proposer: "shora",
    forPoints: 250,
    againstPoints: 6030,
    status: "end in 18h45m",
    statusColor: "bg-green-500",
    comments: "I think",
  },
  {
    id: 3,
    title: "Add hunter system(future version)",
    proposer: "OwnerofJK",
    forPoints: 7000,
    againstPoints: 30,
    status: "closed",
    statusColor: "bg-purple-500",
    comments: "",
  },
  {
    id: 4,
    title: "Introduce New Voting Mechanism",
    proposer: "crypto123",
    forPoints: 1200,
    againstPoints: 450,
    status: "end in 2d14h",
    statusColor: "bg-green-500",
    comments: "",
  },
  {
    id: 5,
    title: "Increase Reward Points",
    proposer: "blockchain_guru",
    forPoints: 8000,
    againstPoints: 1500,
    status: "end in 3d6h",
    statusColor: "bg-green-500",
    comments: "",
  },
  {
    id: 6,
    title: "Update Governance Rules",
    proposer: "dao_master",
    forPoints: 500,
    againstPoints: 2500,
    status: "closed",
    statusColor: "bg-purple-500",
    comments: "",
  }
];